data_dir: "../nilm_lf"
max_epochs: 100
batch_size: 96
inplates: 256
midplates: 64
n_heads: 8
dropout: 0.1
n_layers: 6

lr: 1e-3
min_lr: 5e-5

alias:
  {
    "kettle": ["kettle"],
    "microwave": ["microwave"],
    "dishwasher": ["dishwasher", "dish_washer", "dishwaser"],
    "washing_machine": ["washing_machine", "washer_dryer"],
    "fridge": ["fridge", "fridge_freezer", "refrigerator"],
  }

threshs:
  {
    "kettle": 2000,
    "fridge": 50,
    "washing_machine": 20,
    "microwave": 200,
    "dishwasher": 10,
  }

ceils:
  {
    "kettle": 3100,
    "fridge": 300,
    "washing_machine": 2500,
    "microwave": 3000,
    "dishwasher": 2500,
  }
