data_dir: "./data"
max_epochs: 30
batch_size: 64
inplates: 64
midplates: 32
n_heads: 8
dropout: 0.1
n_layers: 6
window_size: 4096
window_stride: 1024

app_alias:
  {
    "ukdale":
      {
        "kettle": ["kettle"],
        "microwave": ["microwave"],
        "dishwasher": ["dishwasher", "dish_washer"],
        "washing_machine": ["washing_machine", "washer_dryer"],
        "fridge": ["fridge", "fridge_freezer"],
        "rice_cooker": ["rice_cooker"],
      },
    "redd":
      {
        "microwave": ["microwave"],
        "dishwasher": ["dishwaser"],
        "fridge": ["refrigerator"],
        "washing_machine": ["washer_dryer"],
      },
  }

train_houses: { "ukdale": ["house_1", "house_5"] }
train_apps:
  {
    "ukdale":
      [
        "kettle",
        "microwave",
        "dishwasher",
        "washing_machine",
        "fridge",
        "rice_cooker",
      ],
  }

test_houses: { "ukdale": ["house_2"] }
test_apps:
  {
    "ukdale":
      [
        "kettle",
        "microwave",
        "dishwasher",
        "washing_machine",
        "fridge",
        "rice_cooker",
      ],
  }
